apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fla-test-gitops
  description: This is GitOps manifest for fla-test   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: gitops
  owner: group:default/guests 
  lifecycle: experimental
  dependsOn:
    - component:fla-test
