apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fla-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fla-test 
  name: fla-test
  namespace: test
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: fla-test 
